Repository dnglab/dnglab, pull requests merged in 2025-02, with the labels that each got.

#508 Add support for Canon RF-S 10-18mm F4.5-6.3 IS STM
  rawler/data/lenses/rf_mount/canon.toml
Labels: lens-support

#510 Fix clean model name for EOS R5 Mark II
  rawler/data/cameras/canon/r5m2.toml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/crm_movie_modes/R5MK2_LightRaw.CRM.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/crm_movie_modes/R5MK2_StandardRaw.CRM.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_CRAW_ISO_125_crop.CR3.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_CRAW_ISO_640_nocrop.CR3.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_RAW_ISO_125_crop.CR3.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_RAW_ISO_125_nocrop_DUSTDATA.CR3.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_RAW_ISO_640_nocrop.CR3.analyze.yaml
  rawler/data/testdata/cameras/Canon/EOS R5 Mark II/raw_modes/Canon EOS R5m2_RAW_ISO_65535_nocrop_ES.CR3.analyze.yaml
Labels: cr3

#512 Fix: EXIF TimezoneOffset must be a vector because it contains two values
  rawler/src/exif.rs
  rawler/src/formats/tiff/value.rs
Labels: bug

#513 Fix: Use canonical address in FTP client address handling
  embedftp/src/client.rs
Labels: bug

#511 Add --keep-mtime flag
  bin/dnglab/dnglab-lib/src/app.rs
  bin/dnglab/dnglab-lib/src/convert.rs
  bin/dnglab/dnglab-lib/src/ftpconv.rs
  bin/dnglab/dnglab-lib/src/jobs/raw2dng.rs
  rawler/src/decoders/mod.rs
  rawler/src/dng/convert.rs
Labels: enhancement
